/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function run(): void;
export function __wbgt_should_trigger_action_when_button_clicked_0(a: number): void;
export function __wbgt_should_create_button_component_1(a: number): void;
export function __wbgt_should_create_navbar_dropdown_container_26(a: number): void;
export function __wbgt_should_create_carousel_dot_component_7(a: number): void;
export function __wbgt_should_create_form_textarea_20(a: number): void;
export function __wbgt_should_create_dropdown_item_27(a: number): void;
export function __wbgt_should_set_style_prop_36(a: number): void;
export function __wbgt_should_generate_random_string_37(a: number): void;
export function __wbgt_should_create_carousel_controls_component_6(a: number): void;
export function __wbgt_should_create_dropdown_item_10(a: number): void;
export function __wbgt_should_create_form_component_11(a: number): void;
export function __wbgt_should_submit_the_form_12(a: number): void;
export function __wbgt_should_create_spinner_30(a: number): void;
export function __wbgt_should_create_form_input_13(a: number): void;
export function __wbgt_should_create_form_group_horizontal_oriented_14(a: number): void;
export function __wbgt_should_create_form_group_vertical_oriented_15(a: number): void;
export function __wbgt_should_create_form_label_17(a: number): void;
export function __wbgt_should_create_form_select_18(a: number): void;
export function __wbgt_should_create_form_submit_19(a: number): void;
export function __wbgt_should_create_modal_component_24(a: number): void;
export function __wbgt_should_hide_modal_component_from_doom_25(a: number): void;
export function __wbgt_should_create_navbar_item_28(a: number): void;
export function __wbgt_should_create_clickable_navbar_item_29(a: number): void;
export function __wbgt_should_create_plain_text_31(a: number): void;
export function __wbgt_should_create_paragraph_text_32(a: number): void;
export function __wbgt_should_create_alert_text_33(a: number): void;
export function __wbgt_should_create_tag_text_34(a: number): void;
export function __wbgt_should_add_delete_icon_tag_text_35(a: number): void;
export function __wbgt_should_create_carousel_dot_component_8(a: number): void;
export function __wbgt_should_create_dropdown_container_9(a: number): void;
export function __wbgt_should_create_a_container_21(a: number): void;
export function __wbgt_should_create_card_with_three_parts_2(a: number): void;
export function __wbgt_should_create_card_with_single_content_3(a: number): void;
export function __wbgt_should_ignore_parts_when_single_content_exist_4(a: number): void;
export function __wbgt_should_create_item_22(a: number): void;
export function __wbgt_should_create_clickable_item_23(a: number): void;
export function __wbgt_should_create_form_input_16(a: number): void;
export function __wbgt_should_create_carousel_container_component_5(a: number): void;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut___A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hed947ddc5f6339c8(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1118ef4e3c9ef6ab(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hae5efbfd5b3222bf(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h926b2e6e925df79d(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hbb6579ce788dbd2e(a: number, b: number, c: number, d: number): void;
