/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function run(): void;
export function __wbgt_should_create_card_with_three_parts_2(a: number): void;
export function __wbgt_should_create_card_with_single_content_3(a: number): void;
export function __wbgt_should_ignore_parts_when_single_content_exist_4(a: number): void;
export function __wbgt_should_create_form_textarea_14(a: number): void;
export function __wbgt_should_trigger_action_when_button_clicked_0(a: number): void;
export function __wbgt_should_create_button_component_1(a: number): void;
export function __wbgt_should_create_form_submit_13(a: number): void;
export function __wbgt_should_create_form_select_12(a: number): void;
export function __wbgt_should_create_form_component_5(a: number): void;
export function __wbgt_should_submit_the_form_6(a: number): void;
export function __wbgt_should_create_form_input_7(a: number): void;
export function __wbgt_should_create_form_group_horizontal_oriented_8(a: number): void;
export function __wbgt_should_create_form_group_vertical_oriented_9(a: number): void;
export function __wbgt_should_create_form_label_11(a: number): void;
export function __wbgt_should_set_style_prop_27(a: number): void;
export function __wbgt_should_generate_random_string_28(a: number): void;
export function __wbgt_should_create_modal_component_18(a: number): void;
export function __wbgt_should_hide_modal_component_from_doom_19(a: number): void;
export function __wbgt_should_create_navbar_item_20(a: number): void;
export function __wbgt_should_create_clickable_navbar_item_21(a: number): void;
export function __wbgt_should_create_plain_text_22(a: number): void;
export function __wbgt_should_create_paragraph_text_23(a: number): void;
export function __wbgt_should_create_alert_text_24(a: number): void;
export function __wbgt_should_create_tag_text_25(a: number): void;
export function __wbgt_should_add_delete_icon_tag_text_26(a: number): void;
export function __wbgt_should_create_form_input_10(a: number): void;
export function __wbgt_should_create_item_16(a: number): void;
export function __wbgt_should_create_clickable_item_17(a: number): void;
export function __wbgt_should_create_a_container_15(a: number): void;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut___A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6f8e486c5d78601c(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h51fad7db25c56e48(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h59669c0ce72b1b02(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h3c2d299f11883948(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hdb6cbfb42655b488(a: number, b: number, c: number, d: number): void;
